<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="PC77334" name="webstoreselenium.qa.testcases.QuoteTest" tests="3" failures="0" timestamp="01 Apr 2019 16:24:31 GMT" time="41.812" errors="1">
  <testcase name="verify_US_quote" time="41.812" classname="webstoreselenium.qa.testcases.QuoteTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at webstoreselenium.qa.utils.TestUtil.clearAndSendKeys(TestUtil.java:66)
	at webstoreselenium.qa.base.TestBase.loginWebMail(TestBase.java:89)
	at webstoreselenium.qa.testcases.QuoteTest.verify_US_quote(QuoteTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- verify_US_quote -->
  <testcase name="verify_US_INTL_quote" classname="webstoreselenium.qa.testcases.QuoteTest">
    <skipped/>
  </testcase> <!-- verify_US_INTL_quote -->
  <testcase name="verify_MCE_quote" classname="webstoreselenium.qa.testcases.QuoteTest">
    <skipped/>
  </testcase> <!-- verify_MCE_quote -->
</testsuite> <!-- webstoreselenium.qa.testcases.QuoteTest -->
